In [1]:
#1.Create a null vector of size 10 but the fifth value which is 1.

import numpy as np 

null_vector = np.zeros(10) 
null_vector[4] = 1 
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [2]:
#2.Create a vector with values ranging from 10 to 49.
import numpy as np

vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np

matrix = np.array([[0,1,2],[3,4,5],[6,7,8]])

print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [4]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np 

list1 = [1,2,0,0,4,0] 

print("Non-zero elements indices:") 

result = np.nonzero(list1) 

print(result)

Non-zero elements indices:
(array([0, 1, 4], dtype=int64),)


In [5]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.

import numpy as np 

arr = np.random.randint(low=1, high=100, size=(10, 10)) 

print("The 10x10 array of random values is:\n") 
print(arr) 

print("\nThe minimum value in the array is:", np.min(arr)) 
print("The maximum value in the array is:", np.max(arr))

The 10x10 array of random values is:

[[37 85 75 61 82 62 34 89  1  5]
 [16  3 72 68 90 49 31 78  2 11]
 [98 19 88 19 15  1  2 18 62 24]
 [75 99 64  3 27 54 53 28 34 54]
 [78 62 35 10  2 47 38 35 27 54]
 [16 59  7 33 93  1 43  5 51  9]
 [37 62 46 75 27 56 50 75  9 65]
 [16 46 75 30 32 84 12 66 23  9]
 [58 87 97 88 57 96 73 20 41 54]
 [45 23 60 41 95 95 21 79 51 17]]

The minimum value in the array is: 1
The maximum value in the array is: 99


In [6]:
#6. Create a random vector of size 30 and find the mean value.


import numpy as np

rand_vector = np.random.randint(1,100,30)

mean_value = np.mean(rand_vector)

print("Random vector is :", rand_vector)
print("Mean value of the vector is :", mean_value)

Random vector is : [30 16 43 23 95 83  2 17 10 87 76 24 68 79 61 50 50 44 53  7 23 18 36 34
 16 82 48 62 48 57]
Mean value of the vector is : 44.733333333333334
